// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddEquipmentForm: typeof import('./src/components/AddEquipmentForm.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    TopMenu: typeof import('./src/components/menu/TopMenu.vue')['default']
  }
}

export { }
