// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddEquipmentForm: typeof import('./src/components/AddEquipmentForm.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    EquipmentList: typeof import('./src/components/EquipmentList.vue')['default']
    EquipmentListPaginator: typeof import('./src/components/EquipmentListPaginator.vue')['default']
    LoadingScreen: typeof import('./src/components/LoadingScreen.vue')['default']
    TopMenu: typeof import('./src/components/menu/TopMenu.vue')['default']
  }
}

export { }
